<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE catalog [
        <!ELEMENT catalog (book)*>
        <!ELEMENT book (author|title|genre|price|publish_date)*>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST price
                currency CDATA #IMPLIED>
        <!ELEMENT publish_date (#PCDATA)>
        ]>
<catalog>
<book>
    <author> &lt; Bruce Eckel &gt; </author>
    <title>Thinking In Java 4th Edition</title>
    <genre>Computer</genre>
    <price currency="USA">40</price>
    <publish_date>2018-02-02</publish_date>
</book>
<book>
    <author>Robert Lafore</author>
    <title>Data Structures and Algorithms</title>
    <genre>Computer</genre>
    <price>30</price>
    <publish_date>2018-01-01</publish_date>
</book>
</catalog>